version: '3'

services:
  app:
    build: .
    env_file:
      - .env

    volumes:
      - .:/app
    working_dir: /app/zoo
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
